

export type Language = 'en' | 'zh';

export const translations = {
  en: {
    loading: {
      steps: [
        'ESTABLISHING SECURE HANDSHAKE...',
        'DECRYPTING BIOMETRICS...',
        'DOWNLOADING NEURAL LINK...',
        'COMPILING MATRIX DATA...',
        'ACCESS GRANTED.'
      ],
      handshake: 'ESTABLISHING SECURE HANDSHAKE...',
      connecting: 'CONNECTING NEURAL NETWORKS...',
      profile: 'AI DECIPHERING PROFILE...',
      init: 'INITIALIZING CONNECTION...',
      retrieving: 'RETRIEVING ARCHIVED DATA...'
    },
    layout: {
      title: 'GITHUB USER REPORT',
      build: 'DATA_BUILD.2025',
      footer: 'Generated by CyberGit © 2025'
    },
    login: {
      title: 'NEURAL_LINK',
      subtitle: 'Identity Verification Required',
      githubBtn: 'CONNECT VIA GITHUB HQ',
      usernamePlaceholder: 'GITHUB_USERNAME (OPTIONAL)',
      tokenPlaceholder: 'PASTE_ACCESS_TOKEN_HERE',
      submitBtn: 'CONFIRM UPLINK',
      decrypting: 'DECRYPTING...',
      manualLink: 'Already have a token? Input Manually',
      aiToggle: 'Enable AI Profiler',
      demoMode: '>> BYPASS SECURITY (DEMO MODE)',
      error: 'ERROR'
    },
    hero: {
      identity: 'IDENTITY_VERIFIED',
      est: 'Est.',
      age: 'Age',
      followers: 'Followers',
      orgs: 'Orgs',
      systemAnalysis: 'System analysis complete. User demonstrates high-velocity code injection and consistent repository maintenance. Optimization targets met.',
      years: 'YRS'
    },
    metrics: {
      core: 'Core_Metrics',
      output: 'Annual Output',
      contributions: 'CONTRIBUTIONS',
      efficiency: 'Target Efficiency',
      commits: 'Total Commits',
      prs: 'Pull Requests',
      issues: 'Issues Resolved',
      reviews: 'Code Reviews'
    },
    languages: {
      title: 'Language_Distribution',
      secondary: 'Secondary Protocols',
      noData: 'No language data detected in sector.'
    },
    heatmap: {
      title: 'Temporal_Activity_Log',
      subtitle: 'Activity Log // 2025 Cycle',
      null: 'NULL',
      max: 'MAX'
    },
    habits: {
      title: 'Behavioral_Patterns',
      chronotype: 'Chronotype_Analysis',
      persistence: 'Persistence_Log',
      longestStreak: 'Longest Streak',
      currentStreak: 'Current Streak',
      days: 'DAYS',
      weekendWarrior: 'WEEKEND_WARRIOR',
      positive: 'POSITIVE',
      negative: 'NEGATIVE',
      categories: {
        night: 'Night Owl',
        morning: 'Early Bird',
        afternoon: '9-to-5 Pro',
        evening: 'Evening Grinder',
        balanced: 'Balanced Coder'
      },
      descriptions: {
        night: 'Most productive during late hours.',
        morning: 'Starts the day with code.',
        afternoon: 'Consistent business hours output.',
        evening: 'Codes after the day job.',
        balanced: 'Activity distributed throughout the day.'
      },
      periods: {
        night: 'Night (00-06)',
        morning: 'Morning (06-12)',
        afternoon: 'Afternoon (12-18)',
        evening: 'Evening (18-24)'
      }
    },
    achievements: {
      title: 'Influence_&_Achievements',
      stars: 'Stars Earned',
      forks: 'Times Forked',
      entropy: 'Code Entropy',
      target: 'High Value Target',
      activeRepo: 'Most active repository',
      levels: {
        deleter: 'THE DELETER',
        monk: 'REFACTOR MONK',
        creator: 'CREATOR'
      },
      levelDescs: {
        deleter: 'Code deleted > added',
        monk: 'Balanced addition/deletion',
        creator: 'Mostly new features'
      }
    },
    community: {
      title: 'Ecosystem_Connectivity',
      ossImpact: 'Open Source Impact',
      extContrib: 'External Contributions',
      ofTotal: 'Of Total PRs',
      philanthropist: 'Open Source Philanthropist',
      philanthropistDesc: 'High volume of external contributions detected.',
      focusInternal: 'Focusing on internal/personal vectors.',
      orgNetwork: 'Organization Network',
      noOrg: 'No Organization Affiliation Detected',
      impactStar: 'Impact Star'
    },
    pr: {
      title: 'Contribution_Efficiency_Matrix',
      mergeRate: 'Merge Rate',
      basedOn: 'Based on recent PRs',
      velocity: 'Avg Merge Time',
      velocityDesc: 'Velocity Metric',
      size: 'Avg PR Size',
      lines: 'Lines Changed',
      scope: 'Scope Impact',
      filesDesc: 'Avg files per PR',
      hours: 'HRS',
      loc: 'LOC',
      files: 'FILES'
    },
    breakdown: {
      title: 'Contribution_Spectrum',
      ops: 'Ops'
    },
    projects: {
      title: 'Project_Matrix',
      topRepos: 'Top_Repositories',
      sortedBy: 'Sorted by Stargazers',
      avgSize: 'Avg Repo Size',
      visibility: 'Visibility',
      public: 'Public',
      private: 'Private',
      topicCloud: 'Topic_Cloud',
      noDesc: 'No description provided.'
    },
    ai: {
      title: 'Neural_Profile_Analysis',
      classification: 'Classification',
      unidentified: 'UNIDENTIFIED_ENTITY',
      incomplete: 'Profile data incomplete.',
      veteran: 'Veteran',
      specialist: 'Specialist',
      creator: 'Creator',
      surfer: 'AI Surfer'
    },
    tags: {
      noData: 'No Data Stream'
    },
    controls: {
      snapshot: 'SAVE_SYSTEM_SNAPSHOT',
      capturing: 'CAPTURING...',
      terminate: 'TERMINATE_SESSION',
      systemConnected: 'SYSTEM CONNECTED',
      scanAccess: 'SCAN_ACCESS_CODE',
      share: 'SHARE_UPLINK',
      sharing: 'ESTABLISHING...',
      linkCopied: 'UPLINK_SECURE'
    }
  },
  zh: {
    loading: {
      steps: [
        '建立安全握手...',
        '解密生物识别...',
        '下载神经链接...',
        '编译矩阵数据...',
        '访问已授权。'
      ],
      handshake: '建立安全握手...',
      connecting: '连接神经网络...',
      profile: 'AI 正在解密档案...',
      init: '正在初始化连接...',
      retrieving: '正在检索归档数据...'
    },
    layout: {
      title: 'GITHUB 用户年报',
      build: '数据构建.2025',
      footer: '由 CyberGit 生成 © 2025'
    },
    login: {
      title: '神经网络链接',
      subtitle: '需要身份验证',
      githubBtn: '通过 GITHUB 连接',
      usernamePlaceholder: 'GITHUB 用户名 (可选)',
      tokenPlaceholder: '在此粘贴访问密钥',
      submitBtn: '访问上行链路',
      decrypting: '解密中...',
      manualLink: '已有密钥？手动输入',
      aiToggle: '启用 AI 分析器',
      demoMode: '>> 绕过安全系统 (演示模式)',
      error: '错误'
    },
    hero: {
      identity: '身份已验证',
      est: '始于',
      age: '码龄',
      followers: '粉丝',
      orgs: '组织',
      systemAnalysis: '系统分析完成。用户显示出高速度的代码注入和持续的仓库维护。优化目标已达成。',
      years: '年'
    },
    metrics: {
      core: '核心指标',
      output: '年度产出',
      contributions: '次贡献',
      efficiency: '目标效率',
      commits: '总提交数',
      prs: '拉取请求',
      issues: '已解决 Issue',
      reviews: '代码审查'
    },
    languages: {
      title: '语言分布',
      secondary: '次级协议',
      noData: '该扇区未检测到语言数据。'
    },
    heatmap: {
      title: '时间活动日志',
      subtitle: '活动日志 // 2025 周期',
      null: '零',
      max: '最强'
    },
    habits: {
      title: '行为模式',
      chronotype: '作息分析',
      persistence: '持久性日志',
      longestStreak: '最长连胜',
      currentStreak: '当前连胜',
      days: '天',
      weekendWarrior: '周末战士',
      positive: '阳性',
      negative: '阴性',
      categories: {
        night: '夜猫子',
        morning: '早起鸟',
        afternoon: '朝九晚五',
        evening: '夜间极客',
        balanced: '平衡编码者'
      },
      descriptions: {
        night: '在深夜效率最高。',
        morning: '用代码开启新的一天。',
        afternoon: '稳定的工作时间产出。',
        evening: '下班后继续编码。',
        balanced: '活动全天分布均匀。'
      },
      periods: {
        night: '深夜 (00-06)',
        morning: '早晨 (06-12)',
        afternoon: '下午 (12-18)',
        evening: '晚上 (18-24)'
      }
    },
    achievements: {
      title: '影响力与成就',
      stars: '获得星标',
      forks: '被复刻数',
      entropy: '代码熵',
      target: '高价值目标',
      activeRepo: '最活跃仓库',
      levels: {
        deleter: '删除者',
        monk: '重构大师',
        creator: '创造者'
      },
      levelDescs: {
        deleter: '删除代码 > 新增',
        monk: '新增与删除平衡',
        creator: '大部分为新特性'
      }
    },
    community: {
      title: '生态系统连接',
      ossImpact: '开源影响力',
      extContrib: '外部贡献',
      ofTotal: '占总 PR',
      philanthropist: '开源慈善家',
      philanthropistDesc: '检测到大量外部贡献。',
      focusInternal: '专注于内部/个人向量。',
      orgNetwork: '组织网络',
      noOrg: '未检测到组织隶属关系',
      impactStar: '影响力之星'
    },
    pr: {
      title: '贡献效率矩阵',
      mergeRate: '合并率',
      basedOn: '基于近期 PR',
      velocity: '平均合并时间',
      velocityDesc: '速度指标',
      size: '平均 PR 大小',
      lines: '行变动',
      scope: '范围影响',
      filesDesc: '平均每 PR 文件数',
      hours: '小时',
      loc: '行',
      files: '文件'
    },
    breakdown: {
      title: '贡献光谱',
      ops: '次操作'
    },
    projects: {
      title: '项目矩阵',
      topRepos: '热门仓库',
      sortedBy: '按星标排序',
      avgSize: '平均仓库大小',
      visibility: '可见性',
      public: '公开',
      private: '私有',
      topicCloud: '话题云',
      noDesc: '未提供描述。'
    },
    ai: {
      title: '神经档案分析',
      classification: '分类',
      unidentified: '不明实体',
      incomplete: '档案数据不完整。',
      veteran: '老兵',
      specialist: '专家',
      creator: '创造者',
      surfer: 'AI 冲浪者'
    },
    tags: {
      noData: '无数据流'
    },
    controls: {
      snapshot: '保存系统快照',
      capturing: '捕获中...',
      terminate: '终止会话',
      systemConnected: '系统已连接',
      scanAccess: '扫描访问代码',
      share: '建立上行链路',
      sharing: '上传中...',
      linkCopied: '链接已复制'
    }
  }
};

export type Translations = typeof translations.en;
